spring.application.name=KnockCollector
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/DBTirocini
spring.datasource.username=postgres
spring.datasource.password=pass

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

